//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.net_Tutorial
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionString
    {
        public int EnterpriseId { get; set; }
        public int ConnectionStringTypeId { get; set; }
        public string ConnectionString1 { get; set; }
        public int CommandTimeout { get; set; }
        public string TemplateFolder { get; set; }
    
        public virtual ConnectionStringType ConnectionStringType { get; set; }
        public virtual Enterprise Enterprise { get; set; }
    }
}
