//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.net_Tutorial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDomainEntities : DbContext
    {
        public UserDomainEntities()
            : base("name=UserDomainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConnectionString> ConnectionStrings { get; set; }
        public virtual DbSet<ConnectionStringType> ConnectionStringTypes { get; set; }
        public virtual DbSet<Enterprise> Enterprises { get; set; }
    }
}
